    <? if($item->className == 'HiddenField'): ?>
       <input <?=$item->attributes ?> />
    <? else: ?>
    <div class="form-group<? if(!$item->isValid()) echo ' has-error'; ?>">
    <? $item->addCssClass('form-control') ?>
        <? if(!$item->hasCssClass('no-label')): ?>
            <label class="control-label" for="<?= $item->id ?>"><?= $item->title ?></label>
        <? endif ?>
        <? if($item->className == 'TextField' && $item->multiLine): ?>
            <textarea <?= $item->attributes->without('value') ?>><?= $item->value ?></textarea>
        <? elseif($item->className == 'UrlSegmentField'): ?>
        <div class="input-group">
            <span class="input-group-addon"><?= $item->pathPrefix ?></span>
            <input <?= $item->attributes ?>/>
        </div>
        <? else: ?>
            <input <?= $item->addCssClass('input-sm')->attributes ?>/>
        <? endif ?>
        <? if($item->description): ?>
        <span class="help-block"><?= $item->description ?></span>
        <? endif ?>
        <? if(!$item->isValid()): ?>
        <? foreach($item->messages as $error): ?>
        <span class="help-inline"><?= $error ?></span>
        <? endforeach ?>
        <? endif ?>
    </div>
    <? endif ?>