<? $item->setAttribute('role','form') ?>

<form <?= $item->attributes ?>>

<? $hasTabs = $item->fields->isTabBar() ?>

<? if($hasTabs): ?>

<? /****************************************************************************
   /
   / Tabs Rendering
   /
   *************************************************************************/ ?>

<?  // Tab-Bar ?>
    <div class="nav-tabs-custom">
        <?= $item->fields ?>
<? else: ?>

<? /****************************************************************************
   /
   / Normal Fieldsets
   /
   *************************************************************************/ ?>

    <div class="box">
        <div class="box-body">
            <?= $item->fields ?>
        </div>
<? endif // No switchable ?>

<? /****************************************************************************
   /
   / Actions/Submit-Button(s)
   /
   *************************************************************************/ ?>

        <div class="clearfix"></div>

        <div class="box-footer">
            <? foreach($item->actions as $action): ?>
                <? if(!$action->cssClasses->contains('btn')): ?>
                    <? if($action->value == 'delete'): ?>
                        <? $action->cssClasses->append('btn')->append('btn-danger') ?>
                    <? else: ?>
                        <? $action->cssClasses->append('btn')->append('btn-primary') ?>
                    <? endif; ?>
                <? endif ?>
                <button type="submit" name="<?= $action->action ?>" value="<?= $action->value ?>" class="<?= $action->cssClasses ?>"><?= $action->title ?></button>
            <? endforeach ?>
            <? foreach (Actions::forItem($item->getModel())->filtered('save') as $action): ?>
                <? $actionClasses = $action->contexts->copy()->append('btn') ?>
                <? if ($action->contexts->contains('danger')): ?>
                <? $actionClasses->append('btn-danger') ?>
                <? elseif ($action->contexts->contains('warning')): ?>
                <? $actionClasses->append('btn-warning') ?>
                <? elseif ($action->contexts->contains('info')): ?>
                <? $actionClasses->append('btn-info') ?>
                <? elseif ($action->contexts->contains('primary')): ?>
                <? $actionClasses->append('btn-primary') ?>
                <? elseif ($action->contexts->contains('success')): ?>
                <? $actionClasses->append('btn-success') ?>
                <? endif ?>
                <button type="button" <?= $action->data ?> name="<?= $action->name ?>" onclick="<?= $action->onClick ?>" class="<?= $actionClasses ?>"><?= $action->title ?></button>
            <? endforeach ?>
        </div> <!-- /.box-footer -->
    </div><!-- div.box -->
</form>