    <? if($item->className == 'HiddenField'): ?>
       <input <?=$item->attributes ?> />
    <? else: ?>
    <div class="form-group<? if(!$item->isValid()) echo ' has-error'; ?>">
    <? $item->addCssClass('form-control') ?>
        <? if(!$item->hasCssClass('no-label')): ?>
            <label class="control-label" for="<?= $item->id ?>"><?= $item->title ?></label>
        <? endif ?>
        <br/>
        <? $defaultImage = '/cmsable/img/no-img.png' ?>
        <div class="image-field-placeholder" data-default-img="<?= $defaultImage ?>">
            <?
                if ($item->value) {
                    $imageUrl = App::make('filedb.model')->getById($item->value)->url;
                    $hasImage = true;
                } else {
                    $imageUrl = $defaultImage;
                    $hasImage = false;
                }
            ?>
            <img style="max-height: 100px; cursor: pointer;" src="<?= $imageUrl ?>" onclick="selectImageForImageDbField(jQuery(this).closest('div.image-field-placeholder')); return false;" />
            <a class="btn btn-danger remove"<?= $hasImage ? '' : 'style="display: none"' ?> onclick="removeImageFromImageDbField(jQuery(this).closest('div.image-field-placeholder'))"><i class="fa fa-times" aria-hidden="true"></i></a>
            <br/>
            <input <?= $item->attributes ?>/>
        </div>
        <? if($item->description): ?>
        <span class="help-block"><?= $item->description ?></span>
        <? endif ?>
        <? if(!$item->isValid()): ?>
        <? foreach($item->messages as $error): ?>
        <span class="help-inline"><?= $error ?></span>
        <? endforeach ?>
        <? endif ?>
    </div>
    <? endif ?>