<? $item->setAttribute('role','form') ?>
<form <?= $item->attributes ?>>

    <!-- div class="box" -->
        <div class="box-body">
            <? $fieldLists = $item->fields->fieldLists() ?>
            <? $fieldListCount = count($fieldLists) ?>
            <? $fieldListIndex = 0 ?>
            <? foreach($item->fields as $field): ?>
                <? if($field->className == 'HiddenField'): ?>
                <input <?=$field->attributes ?> />
                <? else: ?>
                <? if($field instanceof \FormObject\FieldList && !$field->switchable && $fieldListCount > 2): ?>
                        <? if(($fieldListIndex % 2) == 0): ?>
                        <div class="row">
                            <?= $field ?>
                        <? else: ?>
                            <?= $field ?>
                        </div>
                        <? endif ?>
                        <? $fieldListIndex++ ?>
                    <? else: ?>
                    <?= $field ?>
                    <? endif ?>
                <? endif ?>
            <? endforeach ?>
            <div class="clearfix"></div>

            <? foreach($item->actions as $action): ?>
                <? if($action->value == 'delete'): ?>
                    <? $action->cssClasses->append('btn')->append('btn-danger') ?>
                <? else: ?>
                    <? $action->cssClasses->append('btn')->append('btn-primary') ?>
                <? endif; ?>
                <button type="submit" name="<?= $action->action ?>" value="<?= $action->value ?>" class="<?= $action->cssClasses ?>"><?= $action->title ?></button>
            <? endforeach ?>
        </div>
    <!-- /div -->
</form>