<? /****************************************************************************
   /
   / Tabs Rendering
   /
   *************************************************************************/ ?>
        <? $fieldLists = $item->fieldLists() ?>
        <ul id="tabs-<?= $item->id ?>" class="nav nav-tabs">
        <? foreach($fieldLists as $field): ?>
            <li<? if($field->isFirstList()): ?> class="active"<? endif ?>>
                <a href="#<?= $field->id ?>" data-toggle="tab"><?= $field->title ?></a>
            </li>
        <? endforeach ?>
        </ul>

        <div class="tab-content">
            <? foreach($item->fieldLists() as $field): ?>
                <?= $field ?>
            <? endforeach ?>
            <? foreach($item as $field): ?>
                <? if($field->className == 'HiddenField'): ?>
                <input <?=$field->attributes ?> />
                <? endif ?>
            <? endforeach ?>
        </div> <!-- /.tab-content -->