
    <div class="form-group<? if(!$item->isValid()) echo ' has-error'; ?>">
    <? $item->addCssClass('form-control') ?>
        <? if(!$item->hasCssClass('no-label')): ?>
            <label class="control-label" for="<?= $item->id ?>"><?= $item->title ?><? if($item->hasCssClass('required')): ?>*<? endif ?></label>
        <? endif ?>
        <div class="input-group">
            <span class="input-group-addon"><?= $item->pathPrefix ?></span>
            <input <?= $item->addCssClass('input-sm')->attributes ?>/>
        </div>
        <? if($item->description): ?>
        <span class="help-block"><?= $item->description ?></span>
        <? endif ?>
        <? if(!$item->isValid()): ?>
        <? foreach($item->messages as $error): ?>
        <span class="help-inline"><?= $error ?></span>
        <? endforeach ?>
        <? endif ?>
    </div>